name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fake build APK
        run: |
          mkdir output
          echo "APK build success" > output/app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: output/app.apk
